#ifndef LEXER_H
#define LEXER_H

/* Token types - will be generated by Bison, but we define them here for reference */
/* These should match the %token declarations in parser.y */

/* Note: Flex will use yylval (union from Bison) to pass semantic values */
extern int yylineno;      // current line number (Flex provides this)
extern char *yytext;      // current token text (Flex provides this)

/* Flex-generated functions */
int yylex(void);          // get next token
void yyrestart(FILE *f);  // reset lexer with new file

#endif
